version: '3.6'
services:

  domino:   # <- This will be the name of the service we use on command line

    image: hclcom/domino:12.0.0
    container_name: devserver
    hostname: devserver.domino.local
    stop_grace_period: 60s

    # Server setup using V12 automation
    # https://help.hcltechsw.com/domino/12.0.0/admin/inst_onetouch_preparing_sysenv.html
    #
    # SetupAutoConfigure: 1 is from Domino Community image to instruct autosetup to start using V12 features
    # 

    environment:
      SetupAutoConfigure: 1
      SERVERSETUP_SERVER_TYPE: first
      SERVERSETUP_ADMIN_FIRSTNAME: Domino
      SERVERSETUP_ADMIN_LASTNAME: Admin
      SERVERSETUP_ADMIN_PASSWORD: domino4ever
      SERVERSETUP_ADMIN_IDFILEPATH: admin.id
      SERVERSETUP_ORG_CERTIFIERPASSWORD: domino4ever
      SERVERSETUP_SERVER_DOMAINNAME: DominoCamp
      SERVERSETUP_ORG_ORGNAME: DominoCamp
      SERVERSETUP_SERVER_NAME: devserver
      SERVERSETUP_NETWORK_HOSTNAME: devserver.domino.local
      LANG: en_US.UTF-8

    # 
    # Domino runs as "non-root" user but NSD needs Kernel's trace rights to perform diagnostic
    # with cap_add we provide it
    #

    cap_add:
      - SYS_PTRACE

    #
    # We now tell docker which ports we want to expose, by default our ports will be bound to 
    # the a docker network with a dedicated IP
    #

    ports:
      - 1352:1352
      - 80:80
      - 443:443

    volumes:
      - domino_vol:/local/notesdata

volumes:

  domino_vol:
    name: dominocamp_devserver
    external: true
