version: '3.6'
services:

  domino:   # <- This will be the name of the service we use on command line
    
    build:
      context: .
    image: mycustomapp/domino-extra:12.0.0
    container_name: devserver
    hostname: devserver.domino.local
    stop_grace_period: 60s

    # Server setup using V12 automation
    # https://help.hcltechsw.com/domino/12.0.0/admin/inst_onetouch_preparing_sysenv.html
    #
    # SetupAutoConfigure: 1 enables v12 one touch setup process
    # 

    environment:
      SetupAutoConfigure: 1
      SetupAutoConfigureParams: /tmp/setup.json
      LANG: en_US.UTF-8

    # 
    # Domino runs as "non-root" user but NSD needs Kernel's trace rights to perform diagnostic
    # with cap_add we provide it
    #

    cap_add:
      - SYS_PTRACE

    #
    # We now tell docker which ports we want to expose, by default our ports will be bound to 
    # the a docker network with a dedicated IP
    #

    ports:
      - 1352:1352
      - 80:80
      - 443:443

    volumes:
      # Bind mount of the one touch setup configuration
      - ./setup-first.json:/tmp/setup.json

      # Bind mount a local folder to the container.
      # We cannot directly mount under /local/notesdata as it is created after setup
      # We mount at /local/html
      #
      # As soon as the server is setup we shell into the container to create a symbolic link
      #
      # cd /local/notesdata/domino/html
      # ln -s ../../../html/resources resources
      #
      - ./html:/local/html
      # Volume mount for data
      - domino_vol:/local/notesdata

volumes:

  domino_vol:
    name: dominocamp_devserver
    external: true
